package constants

import "go.stellar.af/stellar-ip-ranges/types"

var GEOFEED = types.Geofeed{
	// types.GeofeedEntry{
	// 	Name:        "Orion IPv4 Aggregate",
	// 	Prefix:      "199.34.92.0/22",
	// 	CountryCode: "US",
	// 	RegionCode:  "US-AZ",
	// 	City:        "Phoenix",
	// 	PostalCode:  "85004",
	// },
	// types.GeofeedEntry{
	// 	Name:        "Orion IPv4 Aggregate",
	// 	Prefix:      "216.250.230.0/23",
	// 	CountryCode: "US",
	// 	RegionCode:  "US-AZ",
	// 	City:        "Phoenix",
	// 	PostalCode:  "85004",
	// },
	types.GeofeedEntry{
		//Name:        "Orion PHX01 IPv4",
		Prefix:      "64.22.120.0/23",
		CountryCode: "US",
		RegionCode:  "US-AZ",
		City:        "Phoenix",
		PostalCode:  "85004",
	},
	types.GeofeedEntry{
		//Name:        "Orion IPv6 Aggregate",
		Prefix:      "2604:c0c0::/32",
		CountryCode: "US",
		RegionCode:  "US-AZ",
		City:        "Phoenix",
		PostalCode:  "85004",
	},
	types.GeofeedEntry{
		//Name:        "Orion PHX01 IPv4",
		Prefix:      "199.34.92.0/23",
		CountryCode: "US",
		RegionCode:  "US-AZ",
		City:        "Phoenix",
		PostalCode:  "85004",
	},
	types.GeofeedEntry{
		//Name:        "Orion HNL01 IPv4",
		Prefix:      "199.34.94.0/23",
		CountryCode: "US",
		RegionCode:  "US-HI",
		City:        "Honolulu",
		PostalCode:  "96819",
	},
	types.GeofeedEntry{
		//Name:        "Orion CHI01 IPv4",
		Prefix:      "216.250.230.0/24",
		CountryCode: "US",
		RegionCode:  "IS-IL",
		City:        "Chicago",
		PostalCode:  "60608",
	},
	types.GeofeedEntry{
		//Name:        "Orion GVL01 IPv4",
		Prefix:      "216.250.231.0/24",
		CountryCode: "US",
		RegionCode:  "US-SC",
		City:        "Greenville",
		PostalCode:  "29607",
	},
	types.GeofeedEntry{
		//Name:        "Orion PHX01 IPv6",
		Prefix:      "2604:c0c0:1000::/36",
		CountryCode: "US",
		RegionCode:  "US-AZ",
		City:        "Phoenix",
		PostalCode:  "85004",
	},
	types.GeofeedEntry{
		//Name:        "Orion HNL01 IPv6",
		Prefix:      "2604:c0c0:3000::/36",
		CountryCode: "US",
		RegionCode:  "US-HI",
		City:        "Honolulu",
		PostalCode:  "96819",
	},
	types.GeofeedEntry{
		//Name:        "Orion GVL01 IPv6",
		Prefix:      "2604:c0c0:8000::/36",
		CountryCode: "US",
		RegionCode:  "US-SC",
		City:        "Greenville",
		PostalCode:  "29607",
	},
}
